#!/usr/bin/env bash

set -e

export PATH=env/bin:${PATH}

flake8 project --ignore=E128,E501,E401
echo ">> Flake8 Tests Completed"

if [ "$1" == "CI" ]; then
    echo ">> Installing CLI..."
    bash scripts/build
fi

echo ">> All Tests Passed!"
